[package]
name = "rust-sorting-algorithms"
version = "0.1.0"
edition = "2021"
authors = ["Micha <git@michadegroot.nl>"]
rust-version = "1.56"

[dependencies]
rand ="0.8.3"

[package.metadata.precommit]
fmt = "cargo fmt -- --write-mode diff 2>&1"
test = "cargo test 2>&1"
